const path = require('path');

module.exports = {
  appid: '20220923001351955', // appid  去百度开发者平台查看 http://api.fanyi.baidu.com/doc/21
  secret: 'tTm6e6KFKgp7hFOxy_AR', // 密钥
}

module.exports.commons = [
  'tip',
  'all',
  'enable',
  'unable',
  'hint',
  'save',
  'back',
  'quit',
  'ok',
  'sure',
  'cancel',
  'next',
  'last',
  'finish',
  'submit',
  'noEmpty',
  'delete',
  'rename',
  'recover',
  'edit',
  'search',
  'operation',
  'copy',
  'note',
  'copy.success',
  'add',
  'email',
  'phone',
  'age',
  'gender',
  'timeZone',
  'country',
  'name',
  'yes',
  'no',
  'send',
  'change',
  'online',
  'offline',
  'test',
  'signOut',
  'uploadpic',
  'emoji',
  'accessory',
  'firstname',
  'secondname',
  'navMenuError',
  'blank',
  'formatError',
  'day',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
  'none',
  'vcard',
  'map',
  'edited',
  'remove',
  'required',
  'sendFailed',
  'channel',
  'custom',
  'inputPlaceholder',
  'selectPlaceholder',
  'filter',
  'view',
  'reset',
  'store',
  'other',
  'use',
  'domain',
  'verify',
  'close',
  'pagination.total.total',
  'pagination.total.item',
  'pagination.total.range'
];

module.exports.locales = {
  en: path.join(__dirname, '../../src/locales/en/messages/'),
  jp: path.join(__dirname, '../../src/locales/ja/messages/'),
  kor: path.join(__dirname, '../../src/locales/ko/messages/'),
  zh: path.join(__dirname, '../../src/locales/zh/messages/'),
}
// 解决无法重新声明块范围变量“path”
// 报错原因： Commonjs 中没有ESM模块概念，在引用时都默认被抛至全局，因此重复引入，TypeScript报错
// 最简单的解决方法: 在报错的文件底部添加一行代码：export {}。这行代码会「欺骗」tslint 使其认为当前文件是一个 ESModule 模块，因此不存在变量重复声明的可能性
export {}